In [1]:
import numpy as np

### 从列表生成数组

In [6]:
x = [1,2,3]
x = np.array(x)

In [12]:
x

array(['1', '2', '3', 'a', 'b', 'c'], dtype='<U21')

### ndarray里的所有元素类型必须相同

In [8]:
x = [1,2,3,'a','b','c']
x = np.array(x)

In [9]:
x

array(['1', '2', '3', 'a', 'b', 'c'], dtype='<U21')

In [15]:
x = [[3,4,5],
     [2,4,6]]
x = np.array(x)
x

array([[3, 4, 5],
       [2, 4, 6]])

### 不整齐列表的转换

In [17]:
x = [[3,4],
     [2,4,6]]
x = np.array(x)
x

/var/folders/rs/f4xb4l9n7_5b0qrnk1v4sm6h0000gn/T/ipykernel_43289/3233144203.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  x = np.array(x)


array([list([3, 4]), list([2, 4, 6])], dtype=object)

### 用函数生成一些规律性的数组

In [22]:
a = np.zeros(10) # 默认生成浮点数
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
a = np.zeros(10,dtype='int') # 指定生成整数
a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
a = np.zeros((3,4),dtype='int') # 指定生成整数
a

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [28]:
a = np.zeros((3,4,5),dtype='int') # 指定生成整数
a

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]])

In [29]:
a = np.ones((3,4,5),dtype='int') 
a

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [31]:
a = np.eye(4,dtype='int') # 生成单位矩阵
a

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [33]:
a = np.arange(1,5) 
a

array([1, 2, 3, 4])

In [34]:
a = np.arange(-5,10,3) 
a

array([-5, -2,  1,  4,  7])

In [35]:
a = np.arange(-5,10,0.3) 
a

array([-5. , -4.7, -4.4, -4.1, -3.8, -3.5, -3.2, -2.9, -2.6, -2.3, -2. ,
       -1.7, -1.4, -1.1, -0.8, -0.5, -0.2,  0.1,  0.4,  0.7,  1. ,  1.3,
        1.6,  1.9,  2.2,  2.5,  2.8,  3.1,  3.4,  3.7,  4. ,  4.3,  4.6,
        4.9,  5.2,  5.5,  5.8,  6.1,  6.4,  6.7,  7. ,  7.3,  7.6,  7.9,
        8.2,  8.5,  8.8,  9.1,  9.4,  9.7])

### 用函数生成随机数

In [36]:
a = np.random.rand(3,5) # 随机生成0-1之间的小数
a

array([[0.26481035, 0.18148792, 0.82404462, 0.5992274 , 0.02128329],
       [0.40065119, 0.17631188, 0.28124663, 0.04073216, 0.9353668 ],
       [0.69597441, 0.88846171, 0.83116805, 0.25662016, 0.26340802]])

In [37]:
a = np.random.randint(-10,10,(3,5)) # 随机生成指定范围的整数
a

array([[  9,  -6,   2,   7,   8],
       [ -1, -10,   5,   8,   2],
       [ -9,  -8,   4,   0,  -5]])

In [46]:
a = np.random.choice(['程咬金','王昭君','李白'],(3,3)) # 随机抽取指定数据
a

array([['王昭君', '程咬金', '李白'],
       ['王昭君', '程咬金', '程咬金'],
       ['王昭君', '李白', '王昭君']], dtype='<U3')

### 从文件中读取数据生成ndarray

In [47]:
import numpy as np

In [50]:
a = np.loadtxt('data03.txt',delimiter=',',dtype = 'int')
a

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [52]:
a = np.genfromtxt('data03_1.txt',delimiter=',',dtype = 'int',filling_values = 0) # 缺失数据的读取
a

array([[1, 2, 3, 4],
       [2, 0, 4, 5]])