# 数组思维之整体运算

### 数组与一个数字的运算

In [1]:
import numpy as np

In [2]:
a = np.random.randint(1,10,5)
a

array([3, 2, 5, 9, 9])

In [3]:
b = a + 5
b

array([ 8,  7, 10, 14, 14])

In [5]:
x = list(range(1,100000))

In [6]:
%%time
y = [i//3 for i in x]

CPU times: user 11.3 ms, sys: 4.73 ms, total: 16.1 ms
Wall time: 45.4 ms


In [7]:
x2 = np.array(x)

In [8]:
%%time
y2 = x2//3

CPU times: user 3.33 ms, sys: 2.23 ms, total: 5.56 ms
Wall time: 7.3 ms


In [9]:
y2

array([    0,     0,     1, ..., 33332, 33332, 33333])

### 通用函数对一个数组进行整体变换

In [10]:
import numpy as np

In [11]:
x = np.random.randint(-100,100,(3,5))
x

array([[ 97,  -1,  84, -61, -31],
       [-11,  48, -99,  87, -54],
       [ 18,  93,  55,   1, -69]])

In [12]:
y = np.abs(x)
y

array([[97,  1, 84, 61, 31],
       [11, 48, 99, 87, 54],
       [18, 93, 55,  1, 69]])

In [14]:
x = np.random.rand(3,5)
x

array([[0.01571771, 0.93056376, 0.34358798, 0.02378942, 0.39859609],
       [0.59659828, 0.68929976, 0.89929654, 0.67477093, 0.51836293],
       [0.87129756, 0.72272064, 0.28038878, 0.19852014, 0.22224522]])

In [16]:
y= np.round(x,2) # 四舍五入
y

array([[0.02, 0.93, 0.34, 0.02, 0.4 ],
       [0.6 , 0.69, 0.9 , 0.67, 0.52],
       [0.87, 0.72, 0.28, 0.2 , 0.22]])

### 同形数组，对位计算

In [26]:
a = [[1,2,3],
    [2,3,4]]
a = np.array(a)

In [27]:
b = [[4,3,2],
    [5,4,3]]
b = np.array(b)

In [28]:
a + b

array([[5, 5, 5],
       [7, 7, 7]])

In [29]:
np.round(a/b,2)

array([[0.25, 0.67, 1.5 ],
       [0.4 , 0.75, 1.33]])

### 点积运算，左边列数必须等于右边行数,行看左边，列看右边

In [49]:
a = np.random.randint(1,5,(2,3))
b = np.random.randint(1,5,(3,2))

In [50]:
a

array([[3, 1, 4],
       [2, 2, 2]])

In [51]:
b

array([[1, 4],
       [2, 3],
       [1, 1]])

In [53]:
a.dot(b)

array([[ 9, 19],
       [ 8, 16]])