In [1]:
import numpy as np

In [3]:
score = np.array([70,80,96])

In [4]:
np.sum(score) # 求和

246

In [8]:
np.average(score) # 求平均或加权，mean只能单纯平均

82.0

In [13]:
np.mean(score)

82.0

In [12]:
np.average(score,weights = [20,30,50]) 

86.0

In [9]:
np.max(score) 

96

In [10]:
np.min(score) 

70

In [14]:
score.mean()

82.0

### 多维数组的统计运算-怎样描述和指定维度

### 把维度理解成属性或者特征，这是描述数组中每一个数据必须的，也是理解数组维度的关键

In [2]:
import numpy as np
sale_num = np.random.randint(60,100,(4,6))
sale_num

array([[65, 96, 90, 73, 98, 95],
       [67, 82, 91, 73, 97, 83],
       [84, 90, 66, 82, 98, 75],
       [92, 92, 72, 75, 65, 92]])

In [3]:
np.sum(sale_num,axis = 1)

array([517, 493, 495, 488])

In [8]:
np.sum(sale_num,axis = 0) # 模块的函数

array([308, 360, 319, 303, 358, 345])

In [9]:
# axis表示按某个维度进行计算，也可以理解为把某个维度消灭掉

In [10]:
sale_num.sum(axis =0) # 对象的方法

array([308, 360, 319, 303, 358, 345])